import { useNavigate } from 'react-router-dom';
import { GameType } from '@/types';

interface GameCardProps {
  type: GameType;
}

const gameInfo: Record<GameType, { title: string; description: string; icon: string; color: string; gradient: string }> = {
  [GameType.TETRIS]: {
    title: '俄罗斯方块',
    description: '经典消行游戏，旋转、移动、消除，挑战你的极限速度！',
    icon: '🧱',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.SNAKE]: {
    title: '贪吃蛇',
    description: '控制小蛇吃食物，越长越难操控，你能坚持多久？',
    icon: '🐍',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.SOKOBAN]: {
    title: '推箱子',
    description: '动动脑筋，把所有箱子推到目标位置，考验你的空间思维！',
    icon: '📦',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-red-600/20',
  },
  [GameType.FLAPPY_BIRD]: {
    title: 'Flappy Bird',
    description: '点击屏幕控制小鸟飞行，穿越管道，看你能飞多远！',
    icon: '🐦',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-amber-600/20',
  },
  [GameType.G2048]: {
    title: '2048',
    description: '滑动合并数字方块，挑战达到 2048！简单规则，无限策略。',
    icon: '🎯',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  [GameType.MEMORY_MATCH]: {
    title: '记忆翻牌',
    description: '翻开卡牌寻找配对，考验你的记忆力！配对越快分数越高。',
    icon: '🃏',
    color: 'text-pink-400',
    gradient: 'from-pink-600/20 to-purple-600/20',
  },
  [GameType.TIC_TAC_TOE]: {
    title: '井字棋',
    description: '经典双人对战棋，三子连线即胜！支持 AI 对手模式。',
    icon: '⭕',
    color: 'text-sky-400',
    gradient: 'from-sky-600/20 to-blue-600/20',
  },
  [GameType.GAME_OF_LIFE]: {
    title: '生命游戏',
    description: 'Conway 细胞自动机 — 放置细胞，观察生命的涌现与演化！',
    icon: '🧬',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.MINESWEEPER]: {
    title: '扫雷',
    description: '经典格子推理，揭开安全格、标记地雷！三种难度挑战。',
    icon: '💣',
    color: 'text-gray-300',
    gradient: 'from-gray-600/20 to-slate-600/20',
  },
  [GameType.GOMOKU]: {
    title: '五子棋',
    description: '经典连五棋类游戏，支持人机对战和双人对弈！',
    icon: '⚫',
    color: 'text-violet-400',
    gradient: 'from-violet-600/20 to-purple-600/20',
  },
  [GameType.DINO_RUNNER]: {
    title: '跑酷恐龙',
    description: 'Chrome 经典离线小恐龙，跳跃躲避仙人掌，看你能跑多远！',
    icon: '🦖',
    color: 'text-emerald-400',
    gradient: 'from-emerald-600/20 to-teal-600/20',
  },
  [GameType.TRON]: {
    title: '贪吃虫 Tron',
    description: '双人光线对抗！控制光线移动，碰到墙壁或轨迹就输，支持 AI 模式。',
    icon: '⚡',
    color: 'text-lime-400',
    gradient: 'from-lime-600/20 to-green-600/20',
  },
  [GameType.PIPE_MANIA]: {
    title: '接水管',
    description: '放置管道连接水源到出口，让水流通过尽可能长的管道！',
    icon: '🔧',
    color: 'text-blue-400',
    gradient: 'from-blue-600/20 to-cyan-600/20',
  },
  [GameType.BREAKOUT]: {
    title: '打砖块',
    description: '控制挡板反弹球击碎砖块，不同颜色不同分数，挑战你的反应速度！',
    icon: '🧱',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-red-600/20',
  },
  [GameType.PACMAN]: {
    title: '吃豆人',
    description: '经典吃豆人，在迷宫中吃掉所有豆子，躲避幽灵追击！',
    icon: '🟡',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-amber-600/20',
  },
  [GameType.SPACE_INVADERS]: {
    title: '太空射击',
    description: '驾驶飞船消灭外星人阵列，保护掩体，拯救地球！',
    icon: '🚀',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-purple-600/20',
  },
  [GameType.OTHELLO]: {
    title: '黑白棋',
    description: '经典翻转棋，落子翻转对手棋子，占据更多格子获胜！',
    icon: '⚫',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.CHECKERS]: {
    title: '跳棋',
    description: '经典西洋跳棋，吃子连跳，升变为王，击败 AI 对手！',
    icon: '🔴',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-orange-600/20',
  },
  [GameType.PINBALL]: {
    title: '弹珠台',
    description: '经典弹珠台，控制挡板弹射弹珠，碰撞bumper得分！',
    icon: '🎰',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-pink-600/20',
  },
  [GameType.MAHJONG_CONNECT]: {
    title: '连连看',
    description: '找到相同图案的牌面，通过不超过2个拐弯的路径连接消除！',
    icon: '🀄',
    color: 'text-teal-400',
    gradient: 'from-teal-600/20 to-cyan-600/20',
  },
  [GameType.MATCH_3]: {
    title: '消消乐',
    description: '交换相邻宝石，三连消除得分，连锁反应获得更高倍率！',
    icon: '💎',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-yellow-600/20',
  },
  [GameType.SUDOKU]: {
    title: '数独',
    description: '经典数字推理，每行每列每宫1-9不重复，三种难度挑战！',
    icon: '🔢',
    color: 'text-blue-400',
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  [GameType.TETRIS_BATTLE]: {
    title: '方块对战',
    description: '俄罗斯方块双人对战！消行攻击对手，AI对手等你挑战！',
    icon: '⚔️',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-orange-600/20',
  },
  [GameType.FROGGER]: {
    title: '青蛙过河',
    description: '控制小青蛙穿越车流和河流，安全到达对岸！经典街机重现。',
    icon: '🐸',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-lime-600/20',
  },
  [GameType.PONG]: {
    title: '乒乓球',
    description: '经典乒乓对战！控制挡板反弹球，先得7分获胜，支持AI对手。',
    icon: '🏓',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.CONNECT_FOUR]: {
    title: '四子棋',
    description: '双人对战策略棋！选择列落子，先连成四子者获胜，支持AI。',
    icon: '🔴',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-red-600/20',
  },
  [GameType.LIGHTS_OUT]: {
    title: '点灯',
    description: '点击切换灯光，影响相邻格子，目标是全部熄灭！考验逻辑推理。',
    icon: '💡',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-yellow-600/20',
  },
  [GameType.WHACK_A_MOLE]: {
    title: '打地鼠',
    description: '地鼠随机冒出，快速敲击得分！考验反应速度和手眼协调。',
    icon: '🔨',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-amber-600/20',
  },
  [GameType.KLOTSKI]: {
    title: '华容道',
    description: '经典三国滑块益智，移动方块为曹操开路，助其从底部逃脱！',
    icon: '🏯',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-amber-600/20',
  },
  [GameType.SOLITAIRE]: {
    title: '纸牌接龙',
    description: '经典 Windows 纸牌，将牌按花色从 A 到 K 依次移到基础堆！',
    icon: '🃏',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.ASTEROIDS]: {
    title: '小行星',
    description: '经典街机射击！驾驶飞船旋转射击，摧毁四面八方的小行星！',
    icon: '☄️',
    color: 'text-gray-300',
    gradient: 'from-gray-600/20 to-slate-600/20',
  },
  [GameType.AIR_HOCKEY]: {
    title: '空气曲棍球',
    description: '双人桌上曲棍球对决！滑动推杆击球，先得7分获胜，支持AI对手。',
    icon: '🏒',
    color: 'text-blue-400',
    gradient: 'from-blue-600/20 to-cyan-600/20',
  },
  [GameType.FRUIT_NINJA]: {
    title: '水果忍者',
    description: '滑动切割飞出的水果，躲避炸弹，挑战最高连击！',
    icon: '🍉',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-green-600/20',
  },
  [GameType.GALAGA]: {
    title: '小蜜蜂',
    description: '经典街机射击！驾驶战机消灭外星虫群，躲避俯冲攻击！',
    icon: '🐝',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-orange-600/20',
  },
  [GameType.BUBBLE_SHOOTER]: {
    title: '泡泡龙',
    description: '瞄准发射泡泡，三个同色即可消除！清空全部泡泡过关。',
    icon: '🫧',
    color: 'text-pink-400',
    gradient: 'from-pink-600/20 to-purple-600/20',
  },
  [GameType.SNAKE_2P]: {
    title: '双人贪吃蛇',
    description: '双蛇同屏竞技！WASD vs 方向键，比拼谁活到最后！',
    icon: '🐍',
    color: 'text-lime-400',
    gradient: 'from-lime-600/20 to-green-600/20',
  },
  [GameType.MANCALA]: {
    title: '曼卡拉',
    description: '古老非洲播棋策略游戏，收集最多种子获胜！支持AI对手。',
    icon: '🫘',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  [GameType.EIGHT_QUEENS]: {
    title: '八皇后',
    description: '经典棋盘谜题，在8×8棋盘上放置8个互不攻击的皇后！',
    icon: '👑',
    color: 'text-violet-400',
    gradient: 'from-violet-600/20 to-purple-600/20',
  },
  [GameType.CENTIPEDE]: {
    title: '蜈蚣',
    description: '经典街机射击！消灭从顶部蜿蜒而下的蜈蚣，躲避蜘蛛和蝎子！',
    icon: '🐛',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-lime-600/20',
  },
  [GameType.MISSILE_COMMAND]: {
    title: '导弹指挥官',
    description: '发射拦截导弹保护城市！瞄准来袭导弹，保卫最后防线！',
    icon: '🚀',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-orange-600/20',
  },
  [GameType.LUNAR_LANDER]: {
    title: '月球着陆器',
    description: '控制推力安全着陆月球！注意燃料消耗，平稳降落在着陆区！',
    icon: '🌙',
    color: 'text-gray-300',
    gradient: 'from-gray-600/20 to-slate-600/20',
  },
  [GameType.SLIDER_PUZZLE]: {
    title: '滑块拼图',
    description: '经典数字滑块益智，滑动方块将数字按顺序排列！',
    icon: '🧩',
    color: 'text-blue-400',
    gradient: 'from-blue-600/20 to-indigo-600/20',
  },
  [GameType.TOWER_OF_HANOI]: {
    title: '河内塔',
    description: '经典递归益智，将所有圆盘从A柱移到C柱，大盘不能放在小盘上！',
    icon: '🗼',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-yellow-600/20',
  },
  [GameType.DONKEY_KONG]: {
    title: '大金刚',
    description: '经典街机平台跳跃！攀爬梯子、躲避障碍，营救被大金刚抓走的人质！',
    icon: '🦍',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-red-600/20',
  },
  [GameType.DIG_DUG]: {
    title: '挖掘者',
    description: '经典街机挖掘游戏！在地下挖隧道，用气泵消灭怪物，越深分数越高！',
    icon: '⛏️',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.BATTLE_CITY]: {
    title: '坦克大战',
    description: '经典坦克射击！保卫基地，消灭敌方坦克，支持多种地形和道具！',
    icon: '🪖',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-amber-600/20',
  },
  [GameType.MASTERMIND]: {
    title: '猜数字',
    description: '经典逻辑推理！猜出隐藏的数字组合，根据提示逐步推理，考验你的头脑！',
    icon: '🔮',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-violet-600/20',
  },
  [GameType.MAKE_24]: {
    title: '算术24点',
    description: '用4个数字和加减乘除运算，凑出24！锻炼数学思维和速算能力！',
    icon: '🧮',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.COOKIE_CLICKER]: {
    title: 'Cookie Clicker',
    description: '放置类经典！点击生产饼干，购买升级自动产出，看你的饼干帝国能有多大！',
    icon: '🍪',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  [GameType.REACTION_TEST]: {
    title: '反应力测试',
    description: '测试你的反应速度！屏幕变绿后尽快按键，多轮测试取平均值，挑战极限！',
    icon: '⚡',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.ZUMA]: {
    title: '祖玛',
    description: '彩色球沿螺旋轨道前进，射出彩球插入链中，同色三连消除，连锁加分！',
    icon: '🔮',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-violet-600/20',
  },
  [GameType.PIXEL_ART]: {
    title: '涂色画板',
    description: '像素涂色画板！在网格上绘画创作，支持画笔、橡皮擦、填充、取色等工具，多种模板任你选择！',
    icon: '🎨',
    color: 'text-pink-400',
    gradient: 'from-pink-600/20 to-fuchsia-600/20',
  },
  [GameType.SPIROGRAPH]: {
    title: '万花尺',
    description: '经典万花尺 Spirograph！调节参数绘制精美的数学曲线图案，支持多种预设和颜色方案！',
    icon: '🌀',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-green-600/20',
  },
  [GameType.WORDLE]: {
    title: 'Wordle',
    description: '经典猜词游戏！6次机会猜出5字母单词，根据颜色提示推理，考验你的词汇量和逻辑！',
    icon: '🔤',
    color: 'text-emerald-400',
    gradient: 'from-emerald-600/20 to-green-600/20',
  },
  [GameType.GEOMETRY_DASH]: {
    title: '跑跑跳跳',
    description: 'Geometry Dash Lite！方块自动奔跑，按空格跳跃躲避尖刺、方块和柱子，节奏感超强！',
    icon: '🔷',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-cyan-600/20',
  },
  [GameType.CAVE_FLYER]: {
    title: '洞穴飞行',
    description: '驾驶直升机穿越洞穴，按住上升松开下降，躲避地形和障碍物，收集星星加分！',
    icon: '🚁',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-amber-600/20',
  },
  [GameType.GRAVITY_FLIP]: {
    title: '重力翻转',
    description: '角色自动奔跑，按空格翻转重力方向，在天花板和地面之间切换躲避障碍物！',
    icon: '🔄',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-indigo-600/20',
  },
  [GameType.KNIGHTS_TOUR]: {
    title: '骑士巡游',
    description: '国际象棋马走日字，尝试遍历棋盘每一格恰好一次！支持提示和撤销，考验你的策略思维！',
    icon: '♞',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-yellow-600/20',
  },
  [GameType.FALL_DOWN]: {
    title: '下落跑酷',
    description: '控制小球穿过上升平台的间隙，被顶到顶部则游戏结束！速度越来越快，你能坚持多久？',
    icon: '⬇️',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.VIRTUAL_PET]: {
    title: '电子宠物',
    description: '照顾你的虚拟宠物！喂食、洗澡、玩耍、睡觉，保持它的饥饿度、清洁度、快乐度和体力！',
    icon: '🐾',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-pink-600/20',
  },
  [GameType.ZTYPE]: {
    title: '打字练习 ZType',
    description: '单词从天而降，快速输入消灭它们！连击加分、难度递增，挑战你的打字速度和准确度！',
    icon: '⌨️',
    color: 'text-emerald-400',
    gradient: 'from-emerald-600/20 to-cyan-600/20',
  },
  [GameType.WATER_SORT]: {
    title: '水排序',
    description: '将不同颜色的水在试管间倒来倒去，最终让每根试管只有一种颜色！考验逻辑与耐心！',
    icon: '🧪',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.SCREW_PUZZLE]: {
    title: '拧螺丝',
    description: '拧下螺丝让板掉落！按正确顺序拧下所有螺丝，让所有板掉落即可过关！',
    icon: '🔧',
    color: 'text-gray-400',
    gradient: 'from-gray-600/20 to-slate-600/20',
  },
  [GameType.SAND_SIMULATION]: {
    title: '沙盒粒子',
    description: '在网格上绘制沙子、水、石头、火、木头等材质，观察它们按物理规则相互作用！',
    icon: '🏜️',
    color: 'text-yellow-400',
    gradient: 'from-yellow-600/20 to-amber-600/20',
  },
  [GameType.VIDEO_POKER]: {
    title: 'Video Poker',
    description: '经典扑克！发5张牌，选择保留/换牌，根据牌型获得赔率。皇家同花顺800倍！',
    icon: '🃏',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-purple-600/20',
  },
  [GameType.BLACKJACK]: {
    title: '21点 Blackjack',
    description: '经典21点！与庄家比牌点数，尽量接近21点但不超过。支持要牌、停牌、加倍！',
    icon: '🂡',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.SPACE_DODGE]: {
    title: '太空陨石躲避',
    description: '驾驶飞船在太空中躲避陨石，生存越久得分越高！收集能量球加分，速度逐渐递增！',
    icon: '☄️',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-indigo-600/20',
  },
  [GameType.BALLOON_POP]: {
    title: '气球射击',
    description: '用准星瞄准射击上升的气球！不同气球不同分数，连击获得倍率加成，小心炸弹！',
    icon: '🎈',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-pink-600/20',
  },
  [GameType.DOTS_AND_BOXES]: {
    title: '点格棋',
    description: '经典双人策略棋！在点阵中画线围成方格，围成最多方格的玩家获胜，支持AI对手。',
    icon: '⬜',
    color: 'text-indigo-400',
    gradient: 'from-indigo-600/20 to-blue-600/20',
  },
  [GameType.MINI_GO]: {
    title: '围棋 9×9',
    description: '9×9 简化围棋，黑白交替落子，围地多者胜！支持提子、禁入点、劫争等完整规则，AI 对手等你挑战！',
    icon: '♟️',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-yellow-600/20',
  },
  [GameType.HEX]: {
    title: '六角棋 Hex',
    description: '经典策略棋！11×11 六角棋盘，红方连上下、蓝方连左右，先连通对边者胜！支持交换规则和AI对手。',
    icon: '⬡',
    color: 'text-violet-400',
    gradient: 'from-violet-600/20 to-indigo-600/20',
  },
  [GameType.RHYTHM]: {
    title: '音乐节拍',
    description: '音符从顶部下落到判定线，在正确时机按键得分！Perfect/Great/Good判定，连击倍率加成！',
    icon: '🎵',
    color: 'text-pink-400',
    gradient: 'from-pink-600/20 to-purple-600/20',
  },
  [GameType.DOODLE_GOD]: {
    title: '涂鸦上帝',
    description: '组合基础元素创造新事物！从水、火、土、气开始，探索数百种合成配方，成为造物主！',
    icon: '🔬',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-violet-600/20',
  },
  [GameType.CHESS]: {
    title: '国际象棋',
    description: '经典国际象棋，六种棋子各展所长。王车易位、吃过路兵、兵升变，挑战智能AI对手！',
    icon: '♔',
    color: 'text-purple-400',
    gradient: 'from-purple-600/20 to-indigo-600/20',
  },
  [GameType.STICK_FIGHTER]: {
    title: '双人格斗',
    description: '火柴人格斗对战！拳击、踢腿、防御、跳跃，击败对手赢得胜利！支持双人对战和AI模式！',
    icon: '🥊',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-orange-600/20',
  },
  [GameType.SLITHER_IO]: {
    title: '虫虫大作战',
    description: '控制虫子吃食物变长，包围对手使其撞上你的身体！Shift 加速消耗身体，策略与操作并重！',
    icon: '🐛',
    color: 'text-lime-400',
    gradient: 'from-lime-600/20 to-green-600/20',
  },
  [GameType.FREECELL]: {
    title: '空当接龙',
    description: '经典 FreeCell 纸牌！利用4个自由单元格和4个基础堆，将52张牌按花色从A到K完成排序！',
    icon: '🂠',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-teal-600/20',
  },
  [GameType.FOLD_PUZZLE]: {
    title: '折纸拼图',
    description: '彩色网格纸片，通过折叠使其匹配目标图案！选择折线和方向，考验你的空间思维！',
    icon: '📄',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-yellow-600/20',
  },
  [GameType.SLOPE_BALL]: {
    title: '滚球跑酷',
    description: '控制球在斜坡上滚动，左右躲避障碍物，速度越来越快！你能坚持多久？',
    icon: '⚽',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-cyan-600/20',
  },
  [GameType.CHINESE_CHESS]: {
    title: '象棋',
    description: '经典中国象棋，楚河汉界，车马炮兵各显神通。支持人机对战，挑战智能AI！',
    icon: '♟',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-amber-600/20',
  },
  [GameType.TEMPLE_RUN]: {
    title: '神庙逃亡',
    description: '三跑道跑酷！左右切换跑道，跳跃和滑铲躲避障碍，收集金币，速度递增挑战极限！',
    icon: '🏃',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-red-600/20',
  },
  [GameType.SENET]: {
    title: '塞尼特',
    description: '古埃及棋盘游戏！掷棍决定步数，策略移动棋子，吃掉对方棋子，先将所有棋子移出者胜！',
    icon: '🏛',
    color: 'text-amber-700',
    gradient: 'from-amber-800/20 to-yellow-700/20',
  },
  [GameType.TANK_DUEL]: {
    title: '坦克大战',
    description: '双人坦克对决！在战场上操控坦克，利用地形和弹药，击败对手赢得胜利！',
    icon: '🔫',
    color: 'text-olive-400',
    gradient: 'from-green-700/20 to-yellow-700/20',
  },
  [GameType.BASKETBALL_HOOPS]: {
    title: '疯狂投篮',
    description: '调节角度和力度投篮，连续进球有奖励！空心入网3分，60秒挑战最高分！',
    icon: '🏀',
    color: 'text-orange-400',
    gradient: 'from-orange-600/20 to-red-600/20',
  },
  [GameType.FLAPPY_PLANE]: {
    title: '飞行小鸟',
    description: '控制飞机穿越障碍物，收集星星加分！速度逐渐递增，挑战你的反应极限！',
    icon: '✈️',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.JIGSAW_PUZZLE]: {
    title: '拼图游戏',
    description: '将打乱的拼图碎片拖拽到正确位置，完成拼图！4×4网格，多个图案可选，考验你的观察力和耐心！',
    icon: '🧩',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  [GameType.BLOONS]: {
    title: '打气球',
    description: '控制准星投掷飞镖击破沿路径移动的气球！放置飞镖猴自动攻击，10关挑战，多种气球类型！',
    icon: '🎈',
    color: 'text-red-400',
    gradient: 'from-red-600/20 to-pink-600/20',
  },
  [GameType.CTF]: {
    title: '抢旗大战',
    description: '双方队伍在场地中争夺对方旗帜，带回己方基地得分！先得3分获胜，支持AI对手。',
    icon: '🚩',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-red-600/20',
  },
  [GameType.BACKGAMMON]: {
    title: '双陆棋',
    description: '经典双陆棋 Backgammon！掷骰子移动棋子，将所有棋子移到己方内盘后归巢获胜。支持AI对手！',
    icon: '🎲',
    color: 'text-amber-400',
    gradient: 'from-amber-600/20 to-orange-600/20',
  },
  [GameType.PONG_2P]: {
    title: '双人乒乓球',
    description: '经典双人乒乓球对战！P1用W/S控制，P2用↑/↓控制，先到11分且领先2分获胜，支持AI模式！',
    icon: '🏓',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-blue-600/20',
  },
  [GameType.HEAD_SOCCER]: {
    title: '顶球对战',
    description: '双人顶球足球对战！用头和身体顶球、踢球，先到5分获胜，支持AI对手！',
    icon: '⚽',
    color: 'text-green-400',
    gradient: 'from-green-600/20 to-emerald-600/20',
  },
  [GameType.MAHJONG_SOLITAIRE]: {
    title: '麻将消除',
    description: '经典麻将消除游戏！选择配对的自由麻将牌进行消除，清除所有牌即可过关！',
    icon: '🀄',
    color: 'text-teal-400',
    gradient: 'from-teal-600/20 to-cyan-600/20',
  },
  [GameType.SPACE_WAR]: {
    title: '双人射击',
    description: '双人飞船太空对决！旋转推进射击，屏幕包裹，3局2胜，支持AI模式！',
    icon: '🚀',
    color: 'text-cyan-400',
    gradient: 'from-cyan-600/20 to-purple-600/20',
  },
};

export default function GameCard({ type }: GameCardProps) {
  const navigate = useNavigate();
  const info = gameInfo[type];

  return (
    <div
      className="game-card group cursor-pointer rounded-2xl border border-white/5 bg-gp-card p-6 backdrop-blur-sm"
      onClick={() => navigate(`/game/${type}`)}
    >
      <div className={`mb-4 flex h-16 w-16 items-center justify-center rounded-xl bg-gradient-to-br ${info.gradient} text-3xl`}>
        {info.icon}
      </div>
      <h3 className={`font-game text-sm ${info.color} mb-2`}>{info.title}</h3>
      <p className="text-sm leading-relaxed text-gray-400">{info.description}</p>
      <div className="mt-4 flex items-center gap-2 text-xs text-gray-500">
        <span className="rounded-full bg-white/5 px-2 py-1">⌨️ 键盘</span>
        <span className="rounded-full bg-white/5 px-2 py-1">🎯 单人</span>
      </div>
      <div className="mt-4 flex items-center gap-1 text-sm font-medium text-gp-accent opacity-0 transition-opacity group-hover:opacity-100">
        开始游戏
        <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
        </svg>
      </div>
    </div>
  );
}

export { gameInfo };
