/**
 * 核心层 — 随机遭遇事件池模板配置（聚合导出）
 *
 * 4子类型 × 5+模板 = 20+遭遇模板
 *   - combat（战斗）: 5个
 *   - diplomatic（外交）: 5个
 *   - exploration（探索）: 5个
 *   - disaster（天灾）: 5个
 *
 * @module core/event/encounter-templates
 */

// 从子模块导入所有模板
export {
  ENCOUNTER_COMBAT_BANDITS,
  ENCOUNTER_COMBAT_TIGER,
  ENCOUNTER_COMBAT_SCOUT,
  ENCOUNTER_COMBAT_BARBARIAN,
  ENCOUNTER_COMBAT_REBEL,
} from './encounter-templates-combat';

export {
  ENCOUNTER_DIPLO_REFUGEES,
  ENCOUNTER_DIPLO_ENVOY,
  ENCOUNTER_DIPLO_SCHOLAR,
  ENCOUNTER_DIPLO_MERCHANTS,
  ENCOUNTER_DIPLO_ALLY_HELP,
} from './encounter-templates-diplomatic';

export {
  ENCOUNTER_EXPLORE_TOMB,
  ENCOUNTER_EXPLORE_HERMIT,
  ENCOUNTER_EXPLORE_TREASURE_MAP,
  ENCOUNTER_EXPLORE_SECRET_PASSAGE,
  ENCOUNTER_EXPLORE_SPRING,
} from './encounter-templates-exploration';

export {
  ENCOUNTER_DISASTER_DROUGHT,
  ENCOUNTER_DISASTER_FLOOD,
  ENCOUNTER_DISASTER_PLAGUE,
  ENCOUNTER_DISASTER_LOCUST,
  ENCOUNTER_DISASTER_EARTHQUAKE,
} from './encounter-templates-disaster';

// 导入类型用于汇总
import type { EncounterTemplate } from './event-v15.types';
import {
  ENCOUNTER_COMBAT_BANDITS,
  ENCOUNTER_COMBAT_TIGER,
  ENCOUNTER_COMBAT_SCOUT,
  ENCOUNTER_COMBAT_BARBARIAN,
  ENCOUNTER_COMBAT_REBEL,
} from './encounter-templates-combat';
import {
  ENCOUNTER_DIPLO_REFUGEES,
  ENCOUNTER_DIPLO_ENVOY,
  ENCOUNTER_DIPLO_SCHOLAR,
  ENCOUNTER_DIPLO_MERCHANTS,
  ENCOUNTER_DIPLO_ALLY_HELP,
} from './encounter-templates-diplomatic';
import {
  ENCOUNTER_EXPLORE_TOMB,
  ENCOUNTER_EXPLORE_HERMIT,
  ENCOUNTER_EXPLORE_TREASURE_MAP,
  ENCOUNTER_EXPLORE_SECRET_PASSAGE,
  ENCOUNTER_EXPLORE_SPRING,
} from './encounter-templates-exploration';
import {
  ENCOUNTER_DISASTER_DROUGHT,
  ENCOUNTER_DISASTER_FLOOD,
  ENCOUNTER_DISASTER_PLAGUE,
  ENCOUNTER_DISASTER_LOCUST,
  ENCOUNTER_DISASTER_EARTHQUAKE,
} from './encounter-templates-disaster';

// ─────────────────────────────────────────────
// 全部模板汇总
// ─────────────────────────────────────────────

/** 所有遭遇模板列表 */
export const ALL_ENCOUNTER_TEMPLATES: EncounterTemplate[] = [
  // 战斗遭遇
  ENCOUNTER_COMBAT_BANDITS,
  ENCOUNTER_COMBAT_TIGER,
  ENCOUNTER_COMBAT_SCOUT,
  ENCOUNTER_COMBAT_BARBARIAN,
  ENCOUNTER_COMBAT_REBEL,
  // 外交遭遇
  ENCOUNTER_DIPLO_REFUGEES,
  ENCOUNTER_DIPLO_ENVOY,
  ENCOUNTER_DIPLO_SCHOLAR,
  ENCOUNTER_DIPLO_MERCHANTS,
  ENCOUNTER_DIPLO_ALLY_HELP,
  // 探索遭遇
  ENCOUNTER_EXPLORE_TOMB,
  ENCOUNTER_EXPLORE_HERMIT,
  ENCOUNTER_EXPLORE_TREASURE_MAP,
  ENCOUNTER_EXPLORE_SECRET_PASSAGE,
  ENCOUNTER_EXPLORE_SPRING,
  // 天灾人祸
  ENCOUNTER_DISASTER_DROUGHT,
  ENCOUNTER_DISASTER_FLOOD,
  ENCOUNTER_DISASTER_PLAGUE,
  ENCOUNTER_DISASTER_LOCUST,
  ENCOUNTER_DISASTER_EARTHQUAKE,
];

/** 按子类型分组的模板映射 */
export const ENCOUNTER_TEMPLATES_BY_SUBTYPE: Record<string, EncounterTemplate[]> = {
  combat: [
    ENCOUNTER_COMBAT_BANDITS,
    ENCOUNTER_COMBAT_TIGER,
    ENCOUNTER_COMBAT_SCOUT,
    ENCOUNTER_COMBAT_BARBARIAN,
    ENCOUNTER_COMBAT_REBEL,
  ],
  diplomatic: [
    ENCOUNTER_DIPLO_REFUGEES,
    ENCOUNTER_DIPLO_ENVOY,
    ENCOUNTER_DIPLO_SCHOLAR,
    ENCOUNTER_DIPLO_MERCHANTS,
    ENCOUNTER_DIPLO_ALLY_HELP,
  ],
  exploration: [
    ENCOUNTER_EXPLORE_TOMB,
    ENCOUNTER_EXPLORE_HERMIT,
    ENCOUNTER_EXPLORE_TREASURE_MAP,
    ENCOUNTER_EXPLORE_SECRET_PASSAGE,
    ENCOUNTER_EXPLORE_SPRING,
  ],
  disaster: [
    ENCOUNTER_DISASTER_DROUGHT,
    ENCOUNTER_DISASTER_FLOOD,
    ENCOUNTER_DISASTER_PLAGUE,
    ENCOUNTER_DISASTER_LOCUST,
    ENCOUNTER_DISASTER_EARTHQUAKE,
  ],
};
